#!/bin/sh

MODE=""
NODES=""
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
	echo $#'Usage: sub-sub <cluster name> [nodes for parallely processing]'
	exit 1
fi
if [ $# -eq 2 ]; then
	PMODE="-v MODE=-p $2"
	NODES="-pe orte $2"
fi

JOBDATA=jobdata

QSUB="qsub -N step-$1 -o $JOBDATA/step-$1.o -e $JOBDATA/step-$1.e $PMODE -v CLUSTER=$1 $NODES sub.pbs-sge"
echo $QSUB
echo `$QSUB`
